modLoader="javafml"
loaderVersion="[41.0.64,)"
license="CC BY-NC-SA 4.0"
issueTrackerURL="https://github.com/TheCJBrine/bedrock-crafter/issues"

[[mods]] #mandatory
modId="bedrockcrafter"
version="1.3.0-MC1.19.2-Forge"
displayName="Bedrock Crafter"
displayURL="https://www.curseforge.com/minecraft/mc-mods/bedrock-crafter"
logoFile="bedrock_crafter.png"
authors="TheCJBrine"
description='''Allows you to craft bedrock and new bedrock building blocks.'''

[[dependencies.bedrockcrafter]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.64,)"
    ordering="AFTER"
    side="BOTH"
